# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a1fb4b43cf4e3c2475a67a82f8cfa29"
application_url = "https://example.com/"
embedded = true
name = "digitup-back-in-stock-app"
handle = "digitup-back-in-stock-app-1"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
